CREATE TABLE notificationfilters (
id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
userId      BIGINT,
pipeline    VARCHAR(255),
stage       VARCHAR(255),
event           VARCHAR(50),
myCheckin       BOOLEAN
);

ALTER TABLE notificationfilters ADD CONSTRAINT fk_notificationfilters_users FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE;

--//@UNDO

DROP TABLE notificationfilters IF EXISTS CASCADE;