CREATE TABLE environmentVariables (
id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
jobId           BIGINT,
variableName   VARCHAR(255),
variableValue        TEXT
);

--//@UNDO

DROP TABLE environmentVariables;