CREATE TABLE oauthclients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  clientId VARCHAR(255) UNIQUE NOT NULL,
  clientSecret VARCHAR(255) NOT NULL,
  redirectUri VARCHAR(255) NOT NULL,
);

CREATE TABLE oauthauthorizations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  userId VARCHAR(255) NOT NULL,
  oauthClientId BIGINT,
  code VARCHAR(255) UNIQUE NOT NULL,
  expiresAt BIGINT
);

ALTER TABLE oauthauthorizations ADD CONSTRAINT fk_oauth_authorization_oauth_client FOREIGN KEY (oauthClientId) REFERENCES oauthclients(id);

CREATE TABLE oauthtokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  userId VARCHAR(255) NOT NULL,
  oauthClientId BIGINT,
  accessToken VARCHAR(255) UNIQUE NOT NULL,
  refreshToken VARCHAR(255) UNIQUE NOT NULL,
  expiresAt BIGINT
);

ALTER TABLE oauthtokens ADD CONSTRAINT fk_oauth_token_oauth_client FOREIGN KEY (oauthClientId) REFERENCES oauthclients(id);

--//@UNDO

DROP TABLE oauthtokens;
DROP TABLE oauthauthorizations;
DROP TABLE oauthclients;
