CREATE TABLE BuildCauseBuffer (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    pipelineName          VARCHAR(255) ,
    buildCause            BINARY,
    timestamp             TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE BuildCauseBuffer ADD CONSTRAINT unique_build_buffer_pipeline_name UNIQUE (pipelineName);
--//@UNDO

DROP TABLE BuildCauseBuffer