CREATE TABLE materialProperties (
id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
materialId INTEGER,
key VARCHAR(255),
value VARCHAR(255),
UNIQUE (materialId, key)
);

ALTER TABLE materialProperties ADD CONSTRAINT fk_materialProperties_materials FOREIGN KEY (materialId) REFERENCES materials(id) ON DELETE CASCADE;
