module JavaImports
  import com.rits.cloning.Cloner unless defined? Cloner
  import com.thoughtworks.cruise.config.ExecTask unless defined? ExecTask
  import com.thoughtworks.cruise.config.AntTask unless defined? AntTask
  import com.thoughtworks.cruise.config.NantTask unless defined? NantTask
  import com.thoughtworks.cruise.config.RakeTask unless defined? RakeTask
  import com.thoughtworks.cruise.config.FetchTask unless defined? FetchTask
  import com.thoughtworks.cruise.config.TimerConfig unless defined? TimerConfig
  import com.thoughtworks.cruise.config.MagicalCruiseConfigXmlLoader unless defined? MagicalCruiseConfigXmlLoader
  import com.thoughtworks.cruise.config.MailHost unless defined? MailHost
  import com.thoughtworks.cruise.config.AgentConfig unless defined? AgentConfig
  import com.thoughtworks.cruise.config.Approval unless defined? Approval
  import com.thoughtworks.cruise.config.ArtifactPlans unless defined? ArtifactPlans
  import com.thoughtworks.cruise.config.ArtifactPlan unless defined? ArtifactPlan
  import com.thoughtworks.cruise.config.preprocessor.ParamSubstitutionHandler unless defined? ParamSubstitutionHandler
  import com.thoughtworks.cruise.domain.ArtifactType unless defined? ArtifactType
  import com.thoughtworks.cruise.domain.buildcause.BuildCause unless defined? BuildCause
  import com.thoughtworks.cruise.domain.ConfigErrors unless defined? ConfigErrors
  import com.thoughtworks.cruise.config.LdapConfig unless defined? LdapConfig
  import com.thoughtworks.cruise.config.PasswordFileConfig unless defined? PasswordFileConfig
  import com.thoughtworks.cruise.config.CruiseConfig unless defined? CruiseConfig
  import com.thoughtworks.cruise.config.EnvironmentConfig unless defined? EnvironmentConfig
  import com.thoughtworks.cruise.config.EnvironmentVariablesConfig unless defined? EnvironmentVariablesConfig
  import com.thoughtworks.cruise.config.ExecTask unless defined? ExecTask
  import com.thoughtworks.cruise.domain.feed.FeedEntries unless defined? FeedEntries
  import com.thoughtworks.cruise.domain.feed.stage.StageFeedEntry unless defined? StageFeedEntry
  import com.thoughtworks.cruise.config.JobConfigs unless defined? JobConfigs
  import com.thoughtworks.cruise.config.JobConfig unless defined? JobConfig
  import com.thoughtworks.cruise.domain.JobIdentifier unless defined? JobIdentifier
  import com.thoughtworks.cruise.domain.JobInstance unless defined? JobInstance
  import com.thoughtworks.cruise.domain.JobInstances unless defined? JobInstances
  import com.thoughtworks.cruise.domain.JobResult unless defined? JobResult
  import com.thoughtworks.cruise.domain.JobState unless defined? JobState
  import com.thoughtworks.cruise.config.LicenseConfig unless defined? LicenseConfig

  import com.thoughtworks.cruise.domain.MaterialRevisions unless defined? MaterialRevisions
  import com.thoughtworks.cruise.domain.MaterialRevision unless defined? MaterialRevision
  import com.thoughtworks.cruise.domain.materials.dependency.DependencyMaterialRevision unless defined? DependencyMaterialRevision
  import com.thoughtworks.cruise.config.materials.dependency.DependencyMaterial unless defined? DependencyMaterial
  import com.thoughtworks.cruise.config.materials.dependency.DependencyMaterialConfig unless defined? DependencyMaterialConfig
  import com.thoughtworks.cruise.domain.materials.MatchedRevision unless defined? MatchedRevision
  import com.thoughtworks.cruise.domain.materials.Material unless defined? Material
  import com.thoughtworks.cruise.config.materials.Materials unless defined? Materials
  import com.thoughtworks.cruise.domain.materials.MaterialConfig unless defined? MaterialConfig
  import com.thoughtworks.cruise.config.materials.MaterialConfigs unless defined? MaterialConfigs
  import com.thoughtworks.cruise.domain.materials.Modification unless defined? Modification
  import com.thoughtworks.cruise.domain.materials.ModifiedAction unless defined? ModifiedAction
  import com.thoughtworks.cruise.domain.materials.ModifiedFile unless defined? ModifiedFile
  import com.thoughtworks.cruise.config.materials.ScmMaterial unless defined? ScmMaterial
  import com.thoughtworks.cruise.config.materials.ScmMaterialConfig unless defined? ScmMaterialConfig
  import com.thoughtworks.cruise.config.materials.PackageMaterial unless defined? PackageMaterial
  import com.thoughtworks.cruise.config.materials.PackageMaterialConfig unless defined? PackageMaterialConfig
  import com.thoughtworks.cruise.config.materials.svn.SvnMaterial unless defined? SvnMaterial
  import com.thoughtworks.cruise.config.materials.svn.SvnMaterialConfig unless defined? SvnMaterialConfig
  import com.thoughtworks.cruise.config.materials.mercurial.HgMaterial unless defined? HgMaterial
  import com.thoughtworks.cruise.config.materials.mercurial.HgMaterialConfig unless defined? HgMaterialConfig
  import com.thoughtworks.cruise.config.materials.perforce.P4Material unless defined? P4Material
  import com.thoughtworks.cruise.config.materials.perforce.P4MaterialConfig unless defined? P4MaterialConfig
  import com.thoughtworks.cruise.config.materials.git.GitMaterial unless defined? GitMaterial
  import com.thoughtworks.cruise.config.materials.git.GitMaterialConfig unless defined? GitMaterialConfig
  import com.thoughtworks.cruise.config.materials.tfs.TfsMaterialConfig unless defined? TfsMaterialConfig
  import com.thoughtworks.cruise.config.MingleConfig unless defined? MingleConfig
  import com.thoughtworks.cruise.config.ParamConfig unless defined? ParamConfig
  import com.thoughtworks.cruise.config.ParamsConfig unless defined? ParamsConfig
  import com.thoughtworks.cruise.config.PipelineConfigs unless defined? PipelineConfigs
  import com.thoughtworks.cruise.config.PipelineConfig unless defined? PipelineConfig
  import com.thoughtworks.cruise.domain.PipelineDependencyGraphOld unless defined? PipelineDependencyGraphOld
  import com.thoughtworks.cruise.domain.valuestreammap.ValueStreamMap unless defined? ValueStreamMap
  import com.thoughtworks.cruise.domain.PipelineIdentifier unless defined? PipelineIdentifier
  import com.thoughtworks.cruise.domain.PipelinePauseInfo unless defined? PipelinePauseInfo
  import com.thoughtworks.cruise.domain.PipelineTimelineEntry unless defined? PipelineTimelineEntry
  import com.thoughtworks.cruise.config.Resources unless defined? Resources
  import com.thoughtworks.cruise.config.Resource unless defined? Resource
  import com.thoughtworks.cruise.config.SecurityConfig unless defined? SecurityConfig
  import com.thoughtworks.cruise.config.ServerConfig unless defined? ServerConfig
  import com.thoughtworks.cruise.config.StageConfig unless defined? StageConfig
  import com.thoughtworks.cruise.domain.StageIdentifier  unless defined? StageIdentifier
  import com.thoughtworks.cruise.domain.StageIdentifier unless defined? StageIdentifier
  import com.thoughtworks.cruise.domain.StageResult unless defined? StageResult
  import com.thoughtworks.cruise.domain.StageState unless defined? StageState
  import com.thoughtworks.cruise.domain.Stages unless defined? Stages
  import com.thoughtworks.cruise.domain.Stage unless defined? Stage
  import com.thoughtworks.cruise.config.Tasks unless defined? Tasks
  import com.thoughtworks.cruise.domain.Task unless defined? Task
  import com.thoughtworks.cruise.config.TestArtifactPlan unless defined? TestArtifactPlan
  import com.thoughtworks.cruise.domain.testinfo.FailureDetails unless defined? FailureDetails
  import com.thoughtworks.cruise.domain.testinfo.StageTestRuns unless defined? StageTestRuns
  import com.thoughtworks.cruise.domain.testinfo.TestStatus unless defined? TestStatus
  import com.thoughtworks.cruise.config.TrackingTool unless defined? TrackingTool
  import com.thoughtworks.cruise.config.TrackingTool unless defined? TrackingTool
  import com.thoughtworks.cruise.domain.User unless defined? User
  import com.thoughtworks.cruise.i18n.Localizer unless defined? Localizer
  import com.thoughtworks.cruise.i18n.LocalizedMessage unless defined? LocalizedMessage
  import com.thoughtworks.cruise.presentation.GoPluginDescriptorModel unless defined? GoPluginDescriptorModel
  import com.thoughtworks.cruise.presentation.environment.EnvironmentPipelineModel unless defined? EnvironmentPipelineModel
  import com.thoughtworks.cruise.presentation.FlashMessageModel unless defined? FlashMessageModel
  import com.thoughtworks.cruise.presentation.ConfigForEdit unless defined? ConfigForEdit
  import com.thoughtworks.cruise.presentation.pipelinehistory.Environment unless defined? Environment
  import com.thoughtworks.cruise.presentation.pipelinehistory.JobHistory unless defined? JobHistory
  import com.thoughtworks.cruise.presentation.pipelinehistory.NullStageHistoryItem unless defined? NullStageHistoryItem
  import com.thoughtworks.cruise.presentation.pipelinehistory.PipelineGroupModel unless defined? PipelineGroupModel
  import com.thoughtworks.cruise.presentation.pipelinehistory.PipelineInstanceModels unless defined? PipelineInstanceModels
  import com.thoughtworks.cruise.presentation.pipelinehistory.PipelineInstanceModel unless defined? PipelineInstanceModel
  import com.thoughtworks.cruise.presentation.pipelinehistory.PipelineModel unless defined? PipelineModel
  import com.thoughtworks.cruise.presentation.pipelinehistory.StageHistoryPage unless defined? StageHistoryPage
  import com.thoughtworks.cruise.presentation.pipelinehistory.StageInstanceModels unless defined? StageInstanceModels
  import com.thoughtworks.cruise.presentation.pipelinehistory.StageInstanceModel unless defined? StageInstanceModel
  import com.thoughtworks.cruise.presentation.TriStateSelection  unless defined? TriStateSelection
  import com.thoughtworks.cruise.presentation.TriStateSelection unless defined? TriStateSelection
  import com.thoughtworks.cruise.presentation.UserModel unless defined? UserModel
  import com.thoughtworks.cruise.presentation.UserSearchModel unless defined? UserSearchModel
  import com.thoughtworks.cruise.presentation.UserSourceType unless defined? UserSourceType
  import com.thoughtworks.cruise.remote.AgentIdentifier unless defined? AgentIdentifier
  import com.thoughtworks.cruise.server.domain.JobDurationStrategy unless defined? JobDurationStrategy
  import com.thoughtworks.cruise.server.domain.Username unless defined? Username
  import com.thoughtworks.cruise.server.domain.user.PipelineSelections unless defined? PipelineSelections
  import com.thoughtworks.cruise.serverhealth.HealthStateScope unless defined? HealthStateScope
  import com.thoughtworks.cruise.serverhealth.HealthStateType unless defined? HealthStateType
  import com.thoughtworks.cruise.serverhealth.ServerHealthService unless defined? ServerHealthService
  import com.thoughtworks.cruise.serverhealth.ServerHealthStates unless defined? ServerHealthStates
  import com.thoughtworks.cruise.serverhealth.ServerHealthState unless defined? ServerHealthState
  import com.thoughtworks.cruise.server.scheduling.ScheduleOptions unless defined? ScheduleOptions
  import com.thoughtworks.cruise.server.service.AgentRuntimeInfo unless defined? AgentRuntimeInfo
  import com.thoughtworks.cruise.server.service.ChangesetService unless defined? ChangesetService
  import com.thoughtworks.cruise.server.service.PipelineStagesFeedService unless defined? PipelineStagesFeedService
  import com.thoughtworks.cruise.server.service.result.DefaultLocalizedResult unless defined? DefaultLocalizedResult
  import com.thoughtworks.cruise.server.service.result.HttpLocalizedOperationResult unless defined? HttpLocalizedOperationResult
  import com.thoughtworks.cruise.server.service.result.HttpOperationResult unless defined? HttpOperationResult
  import org.apache.commons.httpclient.HttpStatus unless defined? HttpStatus
  import com.thoughtworks.cruise.server.service.result.SubsectionLocalizedOperationResult unless defined? SubsectionLocalizedOperationResult
  import com.thoughtworks.cruise.server.service.UserService unless defined? UserService
  import com.thoughtworks.cruise.server.ui.AgentsViewModel unless defined? AgentsViewModel
  import com.thoughtworks.cruise.server.ui.AgentViewModel unless defined? AgentViewModel
  import com.thoughtworks.cruise.server.ui.JobInstanceModel unless defined? JobInstanceModel
  import com.thoughtworks.cruise.server.ui.StageSummaryModel unless defined? StageSummaryModel
  import com.thoughtworks.cruise.server.ui.StageSummaryModels unless defined? StageSummaryModels
  import com.thoughtworks.cruise.server.ui.ViewCacheKey unless defined? ViewCacheKey
  import com.thoughtworks.cruise.server.util.Pagination unless defined? Pagination
  import com.thoughtworks.cruise.server.util.UserHelper unless defined? UserHelper
  import com.thoughtworks.cruise.util.CruiseConstants unless defined? CruiseConstants
  import com.thoughtworks.cruise.util.SystemEnvironment unless defined? SystemEnvironment
  import com.thoughtworks.cruise.util.SystemUtil unless defined? SystemUtil
  import com.thoughtworks.cruise.util.TimeConverter unless defined? TimeConverter
  import com.thoughtworks.cruise.domain.config.Admin unless defined? JavaImports::Admin
  import java.lang.System unless defined? System
  import java.util.HashMap unless defined? HashMap
  import org.joda.time.Duration unless defined? Duration
  import com.thoughtworks.cruise.listener.BaseUrlChangeListener unless defined? BaseUrlChangeListener
  import com.thoughtworks.cruise.config.Authorization unless defined? Authorization
  import com.thoughtworks.cruise.i18n.LocalizedMessage unless defined? LocalizedMessage
  import com.thoughtworks.cruise.config.PipelineTemplateConfig unless defined? PipelineTemplateConfig
  import com.thoughtworks.cruise.server.domain.xml.StageXmlViewModel unless defined? StageXmlViewModel
  import com.thoughtworks.cruise.server.domain.xml.PipelineXmlViewModel unless defined? PipelineXmlViewModel
  import com.thoughtworks.cruise.server.domain.xml.JobXmlViewModel unless defined? JobXmlViewModel
  import com.thoughtworks.cruise.server.domain.xml.JobPlanXmlViewModel unless defined? JobPlanXmlViewModel
  import com.thoughtworks.cruise.server.domain.xml.UsersXmlViewModel unless defined? UsersXmlViewModel
  import org.dom4j.io.OutputFormat unless defined? OutputFormat
  import org.dom4j.io.XMLWriter unless defined? XMLWriter
  import java.io.ByteArrayOutputStream unless defined? ByteArrayOutputStream
  import com.thoughtworks.cruise.domain.XmlWriterContext unless defined? XmlWriterContext
  import com.thoughtworks.cruise.domain.StageFinder unless defined? StageFinder
  import com.thoughtworks.cruise.domain.Properties unless defined? Properties
  import com.thoughtworks.cruise.domain.Property unless defined? Property
  import com.thoughtworks.cruise.domain.DefaultJobPlan unless defined? DefaultJobPlan
  import com.thoughtworks.cruise.server.ui.JobInstancesModel unless defined? JobInstancesModel
  import com.thoughtworks.cruise.config.CaseInsensitiveString unless defined? CaseInsensitiveString
  import com.thoughtworks.cruise.server.ui.SortOrder unless defined? SortOrder
  import com.thoughtworks.cruise.domain.AgentStatus unless defined? AgentStatus
  import com.thoughtworks.cruise.domain.CruiseConfigRevision unless defined? CruiseConfigRevision
  import com.thoughtworks.cruise.util.TimeProvider unless defined? TimeProvider
  import com.thoughtworks.cruise.util.DateUtils unless defined? DateUtils
  import com.thoughtworks.cruise.domain.AgentRuntimeStatus unless defined? AgentRuntimeStatus
  import com.thoughtworks.cruise.security.CruiseCipher unless defined? CruiseCipher
  import com.thoughtworks.cruise.util.command.UrlArgument unless defined? UrlArgument
  import com.thoughtworks.cruise.presentation.TaskViewModel unless defined? TaskViewModel
  import com.thoughtworks.cruise.presentation.PipelineTemplateConfigViewModel unless defined? PipelineTemplateConfigViewModel
  import com.thoughtworks.cruise.server.service.dd.reporting.ReportingFanInGraph unless defined? ReportingFanInGraph
  import com.thoughtworks.cruise.server.service.lookups.CommandSnippet unless defined? CommandSnippet
  import com.thoughtworks.cruise.util.ProcessManager unless defined? ProcessManager
  import com.thoughtworks.go.plugin.infra.plugininfo.GoPluginDescriptor unless defined? GoPluginDescriptor
  import com.thoughtworks.cruise.config.server.security.ldap.BasesConfig unless defined? BasesConfig
  import com.thoughtworks.cruise.config.server.security.ldap.BaseConfig unless defined? BaseConfig
  import com.thoughtworks.cruise.domain.valuestreammap.DependencyNodeType unless defined? DependencyNodeType
  import com.thoughtworks.cruise.server.service.responses.CruiseConfigOperationalResponse unless defined? CruiseConfigOperationalResponse
  import com.thoughtworks.cruise.domain.packagerepository.PackageRepository unless defined? PackageRepository
  import com.thoughtworks.cruise.domain.packagerepository.PackageDefinition unless defined? PackageDefinition
  import com.thoughtworks.cruise.domain.packagerepository.PackageRepositories unless defined? PackageRepositories
  import com.thoughtworks.cruise.domain.packagerepository.Configuration unless defined? Configuration
  import com.thoughtworks.cruise.domain.packagerepository.ConfigurationProperty unless defined? ConfigurationProperty
  import com.thoughtworks.cruise.domain.packagerepository.Packages unless defined? Packages
  import com.thoughtworks.cruise.domain.PluginConfiguration unless defined? PluginConfiguration
  import com.thoughtworks.cruise.config.update.ConfigUpdateAjaxResponse unless defined? ConfigUpdateAjaxResponse
  import com.thoughtworks.go.plugin.access.packagematerial.PackageMetadataStore unless defined? PackageMetadataStore
  import com.thoughtworks.go.plugin.access.packagematerial.PackageConfigurations unless defined? PackageConfigurations
  import com.thoughtworks.go.plugin.access.packagematerial.PackageConfiguration unless defined? PackageConfiguration
  import com.thoughtworks.cruise.domain.packagerepository.ConfigurationKey unless defined? ConfigurationKey
  import com.thoughtworks.cruise.domain.packagerepository.ConfigurationValue unless defined? ConfigurationValue
  import com.thoughtworks.cruise.domain.packagerepository.EncryptedConfigurationValue unless defined? EncryptedConfigurationValue
  import com.thoughtworks.go.plugin.api.material.packagerepository.Option unless defined? Option
  import com.thoughtworks.go.plugin.access.packagematerial.RepositoryMetadataStore unless defined? RepositoryMetadataStore
  import com.thoughtworks.cruise.server.service.materials.commands.PackageMaterialAddWithNewPackageDefinitionCommand unless defined? PackageMaterialAddWithNewPackageDefinitionCommand
  import com.thoughtworks.cruise.server.service.materials.commands.PackageMaterialAddWithExistingPackageDefinitionCommand unless defined? PackageMaterialAddWithExistingPackageDefinitionCommand
  import com.thoughtworks.cruise.server.service.materials.commands.PackageMaterialUpdateWithNewPackageDefinitionCommand unless defined? PackageMaterialUpdateWithNewPackageDefinitionCommand
  import com.thoughtworks.cruise.server.service.materials.commands.PackageMaterialUpdateWithExistingPackageDefinitionCommand unless defined? PackageMaterialUpdateWithExistingPackageDefinitionCommand
  import com.thoughtworks.cruise.server.service.materials.commands.PackageDefinitionCreator unless defined? PackageDefinitionCreator
  import com.thoughtworks.cruise.util.Pair unless defined? Pair
end